[project]
name = "issi-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dvc>=3.59.1",
    "dvc-s3>=3.2.0",
    "polars>=1.27.1",
]
